### ISSUE TITLE
Ghost counter doesn't match the amount of names

### ISSUE THREAD

**Issue by Giovanninono** [fablue/lime-flutter#7]
Sometimes the value of given ghosts doesnt match the amount of usernames if you tap the names. 
E.g. 4 ghosts are given but only 3 names appear if you tap the overview.

If this is how the ghost mechanic is designed it's a bit confusing.

See attachments.
![2017-06-04 19_30_14-telegramdesktop](https://cloud.githubusercontent.com/assets/29044190/26763904/aacfe16a-495c-11e7-8147-66002d961b57.png)
![2017-06-04 19_31_06-telegramdesktop](https://cloud.githubusercontent.com/assets/29044190/26763903/aac8cde4-495c-11e7-94a3-3a2d5a2af19d.png)

**Comment by fablue** [comment]
You do not have to create a profile to give a ghost! At least not for older versions of the app!
